name: Input Example

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Enter your name'
        required: true
        default: 'Vasudevan'

jobs:
  print-input:
    runs-on: ubuntu-latest

    steps:
      - name: Print the input
        run: echo "Hello ${{ github.event.inputs.name }}"
