
name: GitHub Actions Outputs Example

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      result: ${{ steps.build.outputs.result }}
    steps:
      - name: Build
        id: build
        run: echo "result=asdf" >> "$GITHUB_OUTPUT"
